[project]
name = "medsynth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.88",
    "chromadb>=1.5.9",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "metapub>=0.7.4",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pymed>=0.8.9",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "xmltodict>=1.0.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
